name: Deploy Cloudflare Worker  # 工作流名称
on:
  push:  # 触发条件：代码推送到 main 分支时自动部署
    branches: [main]
  workflow_dispatch:  # 可选：手动触发（用于调试）
    inputs:
      comment:
        description: 'Manual deployment comment'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 运行环境
    steps:
      - name: Checkout code  # 拉取代码到运行环境
        uses: actions/checkout@v4

      - name: Install Wrangler CLI  # 安装 Cloudflare Wrangler 工具
        run: |
          npm install -g wrangler@4.20.0  # 固定版本，避免兼容性问题

      - name: Deploy to Cloudflare Workers  # 核心部署步骤
        run: |
          wrangler publish --force --no-telemetry  # --force 跳过交互式确认，--no-telemetry 禁用遥测
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}  # GitHub 仓库中存储的 Cloudflare API 令牌
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}  # Cloudflare 账户 ID
